/* content/en.js — English strings, keyed by data-i18n. */
window.CONTENT_EN = {
  "meta.title": "Samir El Taibe · From accounting to decision-making",
  "meta.desc": "Portfolio of Samir El Taibe, financial and administrative coordinator in Brussels. General accounting, closings, reporting, budgets, VAT, process improvement.",
  "cv.reco": "Download the recommended CV:",
  "cv.alt": "Alternative:",
  "cv.autres": "See other versions",
  "cv.cibles": "See my targeted CVs",
  "cv.parcours": "Discover my career path",
  "cv.note_en": "One English CV is currently available (Experienced Accountant). Other versions are available in French.",
  "lang.badge": "Targeted CV",
  "u.cpt.p2": "I make the figures reliable and keep them secure",
  "dash.etats": "States: checked · substantiated · carried forward",

  "nav.cpt": "Accounting", "nav.fin": "Finance", "nav.hum": "Samir",
  "nav.print": "Print this portfolio", "nav.skip": "Skip to content",

  "hero.eyebrow": "Samir El Taibe · Financial and administrative coordinator · Brussels",
  "hero.h1": "FROM ACCOUNTING TO DECISION-MAKING",
  "hero.sub": "Numbers are the starting point, not the end goal.",
  "hero.pres": "Trained in finance, then specialised in accounting, I secure the books, turn data into reliable analysis and make financial information useful to decision-makers.",
  "hero.r1": "8+ years of experience", "hero.r2": "2 entities", "hero.r3": "4 team members coordinated",
  "hero.r4": "general accounting", "hero.r5": "reporting and budgets", "hero.r6": "process improvement",
  "hero.cta1": "Discover the case studies",
  "hero.manifesto": "Understand. Secure. Create value.",

  "dash.cpt.t": "Monthly closing, from D+1 to D+8",
  "dash.s1": "Cut-off", "dash.s2": "Bank reconciliations", "dash.s3": "GL check (AP, AR, assets)",
  "dash.s4": "Variance analysis (correction loop)", "dash.s5": "Adjusting entries",
  "dash.s6": "Account substantiation", "dash.s7": "Reporting",
  "dash.cpt.note": "Method illustration: typical monthly closing across two entities. Full BPMN model on the Process page.",
  "dash.cpt.link": "See the BPMN model",
  "dash.fin.t1": "Treasury reporting automation",
  "dash.fin.avant": "Before: several manual steps", "dash.fin.apres": "After: controlled refresh",
  "dash.fin.l1": "Near-complete automation of production. Schematic view.",
  "dash.fin.link": "Read the case study",
  "dash.fin.t2": "Budget vs actuals",
  "dash.fin.fict": "Demonstration with fictitious data.",
  "dash.b1": "Staff", "dash.b2": "Operations", "dash.b3": "Projects", "dash.b4": "Investments",
  "dash.hum.t": "The path in eight milestones",
  "dash.j1": "Bachelor's, banking management", "dash.j2": "Master's, financial operations",
  "dash.j3": "Firms and banking", "dash.j4": "Industry", "dash.j5": "Belgium",
  "dash.j6": "EPHEC (finalising)", "dash.j7": "Coordinating 2 entities", "dash.j8": "ITAA objective",

  "b.intro": "One career path. Three reading angles.",
  "b.sub": "Choose what you want to explore.",
  "b.frame": "Three facets of one profession, not three different profiles.",
  "u.cpt.n": "Accounting", "u.cpt.p": "I make the figures reliable and keep them secure.",
  "u.fin.n": "Finance", "u.fin.p": "I analyse and I anticipate.",
  "u.hum.n": "Samir", "u.hum.p": "I explain, I coordinate and I keep progressing.",

  "u.cpt.txt": "Hands-on accountant with more than eight years of experience in general accounting across several entities. I post the entries (provisions, depreciation, sundry operations, adjustments), I reconcile and substantiate balance sheet and income accounts, and I explain variances. I run monthly and annual closings, prepare the annual accounts and audit files with the statutory auditor, and follow VAT and tax obligations. Reference person for the accounting tools on Adfinity, trained in SAP FI (Key User track), I document procedures and secure the postings.",
  "u.fin.txt": "Trained in finance (master's in financial operations), I deliver the reporting and budget monitoring of two entities: budget construction and follow-up, variance analysis between actuals and forecast, dashboards for Management and subsidising authorities. I structure data from heterogeneous sources into indicators people can decide on. Advanced Excel, cost accounting and automation are part of my daily practice.",
  "u.hum.sub": "How I work",
  "u.hum.txt": "An accurate figure is useless if nobody understands it. I spend as much time explaining a variance as computing it, and I have learned that clarity beats demonstration. I coordinate a team of four across two entities, I work with Management, the statutory auditor and funding bodies, and I make sure everyone knows why we do things, not only how.",

  "cy.t": "Scope covered", "cy.e": "Seven cycles",
  "cy1.b": "Purchases and suppliers", "cy1.p": "Entry, posting checks, supplier cycle, schedules and payment preparation.",
  "cy2.b": "Sales and customers", "cy2.p": "Receivables follow-up, matching, customer account reconciliation.",
  "cy3.b": "Fixed assets", "cy3.p": "Asset register, depreciation schedules, addition and disposal entries.",
  "cy4.b": "Treasury", "cy4.p": "Day-to-day monitoring, bank reconciliations, payments via Isabel, income and expenses.",
  "cy5.b": "Tax", "cy5.p": "VAT returns, periodic obligations, proactive adjustments and filing preparation.",
  "cy6.b": "Closing and annual accounts", "cy6.p": "Provisions, sundry entries, account substantiation, auditor file.",
  "cy7.b": "Analytics and subsidies", "cy7.p": "Project-based postings, subsidised expense justification, funder audit responses.",

  "ch.t": "From data to decision",
  "ch1.b": "Sources", "ch1.p": "Accounting of two entities, activity data, budgets and subsidy agreements.",
  "ch2.b": "Structuring", "ch2.p": "Combination, consistency checks, project-based analytical postings.",
  "ch3.b": "Analysis", "ch3.p": "Actuals vs budget vs trajectory. Costs and profitability by activity.",
  "ch4.b": "Restitution", "ch4.p": "Excel dashboards, financial and operational indicators, monthly reporting.",
  "ch5.b": "Decision", "ch5.p": "Management and subsidising authorities. Substantiated budget trade-offs.",

  "tr.t": "How I work",
  "tr1.b": "Calm under pressure", "tr1.p": "A closing is played out over a few days. I prefer a steady pace and a calm team to permanent urgency.",
  "tr2.b": "Pedagogy", "tr2.p": "I explain a variance, a posting or a procedure to someone who is not an accountant, without jargon and without condescension.",
  "tr3.b": "Transmission", "tr3.p": "I write procedures so the work survives my absence. A role that depends on one person is a risk.",
  "tr4.b": "Good spirits", "tr4.p": "I laugh easily and smile a lot. It takes nothing away from rigour; it just makes the days shorter.",
  "insp.t": "What inspires me",
  "insp1": "Coffee: hospitality, precision and consistency, at the same level every day.",
  "insp2": "Video games and manga: a taste for well-built systems and for narrative. Persona 5 inspired the visual identity of this site.",
  "insp3": "Sport: progressing through repetition, without skipping steps.",
  "insp4": "Tools: understanding how something works in order to make it work better.",

  "c.t": "What my CV does not show",
  "c.intro": "My CV lists my responsibilities. This portfolio shows how I work, how I solve problems and what results I obtain.",
  "lbl.ctx": "Context", "lbl.pb": "Problem", "lbl.ana": "Analysis", "lbl.act": "Action",
  "lbl.res": "Result", "lbl.comp": "Skills demonstrated", "lbl.learn": "What I learned",

  "cs1.t": "Treasury reporting automation",
  "cs1.ctx": "Treasury monitoring of two entities in Excel, updated regularly for coordination and Management.",
  "cs1.pb": "Production relied on a chain of manual steps: extractions, copy-paste across tabs, reformatting, line-by-line checking. Every manual step was an opportunity for error, and production time limited the monitoring frequency.",
  "cs1.ana": "The file mixed three layers: raw data, calculations and presentation. As long as they stayed intertwined, every update meant redoing everything.",
  "cs1.act": "Rebuilt the file in separate layers: structured data import, isolated calculation area, built-in consistency checks, automatic output formatting.",
  "cs1.res": "Near-complete automation of production; time shifts from building the file to analysing the balances.",
  "cs1.comp": "Advanced Excel, data structuring, internal control, automation, treasury.",
  "cs1.learn": "Automation is only worth it if the checks are built in. Saving time without securing it just moves the problem.",

  "cs2.t": "Closing cycle reorganisation",
  "cs2.ctx": "Monthly closings of two entities, with tight reporting deadlines.",
  "cs2.pb": "Variances detected late forced controls that had already passed to be replayed; the end of the cycle absorbed the delays of the beginning.",
  "cs2.ana": "The order of the controls did not follow their blocking power: some late checks actually conditioned steps already completed.",
  "cs2.act": "Reordered controls and reconciliations, blocking checks moved to the head of the cycle, tighter correction loop. The process is modelled in BPMN on the Process page.",
  "cs2.res": "Shorter closing cycle and fewer backtracks.",
  "cs2.comp": "Closings, reconciliations, process organisation, BPMN modelling.",
  "cs2.learn": "In a closing, the order of the controls matters as much as the controls themselves.",

  "cs3.t": "VAT anomaly detection and correction",
  "cs3.ctx": "Periodic VAT returns and tax obligations of the entities managed.",
  "cs3.pb": "Potential inconsistencies between the accounts and the declared bases.",
  "cs3.ana": "Systematic cross-check of declared bases against the accounts, identification of the origin of the variances.",
  "cs3.act": "Proactive correction before any external audit, then recurring checks upstream of each return.",
  "cs3.res": "Proactive detection and correction of VAT anomalies before any audit, securing the compliance of the returns.",
  "cs3.comp": "VAT, tax compliance, internal control, documentation rigour.",
  "cs3.learn": "Correcting yourself always costs less than being corrected.",

  "cs4.t": "Multi-entity reporting standardisation",
  "cs4.ctx": "Reports for Management and subsidising authorities, produced for two entities from heterogeneous sources.",
  "cs4.pb": "Different templates depending on the recipient, high processing time, risks of inconsistency between versions.",
  "cs4.ana": "The multiplication of formats came from the absence of a common data base; every report started from scratch.",
  "cs4.act": "Standardised templates and sources, project-based analytical postings, systematic consistency checks before release.",
  "cs4.res": "Significantly reduced processing time and a single data base for all recipients.",
  "cs4.comp": "Multi-entity reporting, cost accounting, data reliability, financial communication.",
  "cs4.learn": "Good reporting is standardised at the source, not at the formatting stage.",

  "d.t": "The essentials in 60 seconds",
  "d.pos.l": "Positioning", "d.pos.v": "From accounting to decision-making.",
  "d.job.l": "Current role", "d.job.v": "Financial and administrative coordinator, Mission Locale de Molenbeek and Molenbeek Formation (non-profits, Brussels), since 2024.",
  "d.exp.l": "Experience", "d.exp.v": "More than eight years in accounting and finance, in Morocco then Belgium.",
  "d.res.l": "Four results",
  "d.res.v": "Near-complete automation of treasury reporting · significantly reduced report processing time · shorter closing cycle through reorganised controls · proactive detection and correction of VAT anomalies before any audit.",
  "d.comp.l": "Skills", "d.comp.v": "General accounting, monthly and annual closings, annual accounts, VAT and tax obligations, treasury and payments, reporting and budgets, cost accounting, procedures and internal control.",
  "d.tools.l": "Tools", "d.tools.v": "Adfinity, Isabel, advanced Excel, Winbooks, Popsy, SAP FI (Key User training).",
  "d.form.l": "Education", "d.form.v": "Master's in international financial operations (2015) · Bachelor's in accounting, tax orientation, EPHEC, finalising.",
  "d.lang.l": "Languages", "d.lang.v": "Fluent French (working language) · Arabic (native) · Intermediate professional English: good written comprehension, effective written communication, spoken fluency improving.",
  "d.contact.l": "Contact",

  "e.t": "Career path",
  "e.msg": "Initial training in finance, operational experience, then a deliberate specialisation in Belgian accounting.",
  "tl1": "Bachelor's degree in banking management, HBF, Oujda",
  "tl2": "Master's degree in international financial operations, HBF, Oujda",
  "tl3": "Junior accountant and tax assignments in firms: Somnium, Cabinet Aderghal, BMCI",
  "tl4": "Financial assistant, Casamarmol and Granit, Casablanca",
  "tl5": "Financial and administrative manager, Marbre El Yamani, Nador: coordination of accounting and administrative work",
  "tl6": "Settling in Belgium: adapting to the Belgian accounting framework, equivalences, preparing the return to studies",
  "tl7": "Back to studies at EPHEC: bachelor's in accounting, tax orientation",
  "tl8": "Accounting assignment, We-Care non-profit, Brussels",
  "tl9": "Financial and administrative coordinator, Mission Locale de Molenbeek and Molenbeek Formation",
  "tl10": "Continuing my path towards ITAA certification",
  "tl.h": "Horizon",

  "f.txt": "This model shows how I structure and control a monthly closing across two entities.",
  "f.link": "See the process page (BPMN)",
  "f.note": "Process diagrams are provided in French.",

  "g.t": "How I keep progressing",
  "g.txt": "I see expertise as a continuous journey. After initial training in finance, I went back to school in accounting in Belgium to consolidate my practice and gradually pursue my ITAA certification objective.",

  "h.t": "Let's talk",
  "h.lead": "You have discovered my career path. Let's now discuss your needs.",
  "h.mail": "Send an email", "h.li": "Open LinkedIn",
  "h.all": "All targeted CVs, by family",
  "fam.accounting": "Accounting", "fam.finance": "Finance", "fam.process": "Processes and ERP", "fam.english": "English",

  "foot.colophon": "Greek opens this site as a metaphor for translation: from the language of numbers to the language of decision.",
  "foot.made": "Hand-built in native HTML, CSS and JavaScript, with no framework."
};
